services:
  - type: web
    name: planmymeals
    env: python
    pythonVersion: 3.10.0
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn PlanMyMealsServer:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false  
      - key: RENDER
        value: true
      - key: PYTHON_VERSION
        value: 3.10.0

